spring:
  application:
    name: music-band
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-tls-skip-verify: true
        enabled: true
        register: true
        instance-id: ${spring.application.name}-${server.port}-${random.uuid}
        health-check-path: /actuator/health
        health-check-interval: 10s
        health-check-timeout: 5s
        scheme: https

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

server:
  port: 8082
  ssl:
    enabled: true
    key-store: classpath:static/keystore.jks
    key-store-password: password
    key-store-type: JKS
    key-alias: wildfly
